spring:
  application:
    name: api-service
  devtools:
    remote:
      secret: thisismysecret
  data:
    rest:
      base-path: /api
      detection-strategy: visibility
    mongodb:
      database: gtm-api
#server:
#  port: 8080