version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
  redis:
    image: redis:4-alpine
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  mongo:
    image: mongo:3.6.4
    ports:
      - "27017:27017"
    volumes:
      - api_db:/data/db
  api-server:
    image: twigcodes/api
    ports:
      - "8080:8080"
      - "5005:5005"
    links:
      - mongo
      - redis
      - elasticsearch
volumes:
  api_db: {}
  redis-data: {}
  esdata: {}
