version: '3.2'
services:
  redis:
    image: redis:4-alpine
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    hostname: redis
  mongo:
    image: mongo:3.6.4
    ports:
      - "27017:27017"
    volumes:
      - api_db:/data/db
  api-server:
    image: api
    ports:
      - "8080:8080"
      - "5005:5005"
    links:
      - mongo
      - "redis:redis"
volumes:
  api_db: {}
  redis-data: {}
