spring:
  application:
    name: api-service
  profiles:
    active: dev
  data:
    mongodb:
      database: gtm-api
  cache:
    type: redis
  redis:
    host: redis
server:
  port: 8080
logging:
  level:
    org.apache.http: ERROR
    org.springframework:
      web: ERROR
      data: ERROR
      security: ERROR
      cache: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: ERROR
    dev.local.gtm.api: ERROR

---

spring:
  profiles: dev
  devtools:
    remote:
      secret: thisismysecret
  data:
    mongodb:
      database: gtm-api-dev
  redis:
    host: localhost
logging:
  level:
    org.apache.http: DEBUG
    org.springframework:
        web:
          client.RestTemplate: DEBUG
        data: DEBUG
        security: DEBUG
        cache: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    dev.local.gtm.api: DEBUG

---

spring:
  profiles: test
  data:
    mongodb:
      database: gtm-api-test
  cache:
    type: none
logging:
  level:
    org.apache.http: DEBUG
    org.springframework:
          web:
            client.RestTemplate: DEBUG
          data: DEBUG
          security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    dev.local.gtm.api: DEBUG
---

spring:
  profiles: prod

